sources:
  - HonkExportFile.glyphs
axisOrder:
  - MORF
  - SHDW
familyName: Honk
buildVariable: true
buildStatic: false
stat:
  - name: Morph
    tag: MORF
    values:
    - name: Default
      value: 15
  - name: Shadow
    tag: SHDW
    values:
    - name: Default
      value: 0
